From java:8
WORKDIR /usr/app
copy ./target/springdata-jpa-example-0.0.1-SNAPSHOT.jar /usr/app
run sh -c 'touch springdata-jpa-example-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-jar","springdata-jpa-example-0.0.1-SNAPSHOT.jar"]
