server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://mysql-standalone:3306/emsdb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

security:
  oauth2:
    resource:
      token-info-uri: http://dockeroauth:8686/oauth/check_token
    client:
      client-id: web
      client-secret: webpass