spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsdb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8282

security:
  oauth2:
    client:
      client-id: web
      client-secret: webpass
    resource:
      token-info-uri: http://localhost:8686/oauth/check_token