server:
  port: 8383

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
