spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  servlet:
    session:
      cookie:
        name: KSESSIONID

security:
  oauth2:
    client:
      client-id: web
      client-secret: webpass
      user-authorization-uri: http://localhost:8484/oauth/authorize
      access-token-uri: http://localhost:8484/oauth/token
    resource:
      token-info-uri: http://localhost:8484/oauth/check_token